apiVersion: v1
 kind: Config

 clusters:
   - name: self-hosted-cluster
     cluster:
        certificate-authority-data: <replace this with certificate-authority-data info>
        server: <replace this with server info>

 users:
 - name: svcs-acct-dply
      user: svcs-acct-dply
      token: <replace this with token info>


 contexts:
 - name: svcs-acct-context
   context:
	 cluster:  self-hosted-cluster
	 user: svcs-acct-dply


 current-context: svcs-acct-context