echo -n 'admin' | base64
YWRtaW4=
echo -n '1f2d1e2e67df' | base64
MWYyZDFlMmU2N2Rm

apiVersion: v1
kind: Secret

metadata:
  name: credentials
  namespace: default
  type: Opaque

data:
  password: MWYyZDFlMmU2N2Rm
  username: YWRtaW4=


    apiVersion: v1
    kind: Secret

    metadata:
      name: db-secret

    data:
      DB_Host: c3FsMDE=
      DB_User: cm9vdA==
      DB_Password: cGFzc3dvcmQxMjM=



