apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: LoadBalancer

  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376
      nodePort: 30003

  selector:
    app: MyApp

status:
  loadBalancer:
    ingress:
    - ip: 192.0.2.127